name = "chook-check-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "chook-check"
database_id = "3183660c-38a8-418c-a360-388acd20869c"
migrations_dir = "migrations"

[triggers]
crons = ["0 * * * *"]
